// productList
export const DATA_RQEUST = "DATA_RQEUST";
export const DATA_FETCH_FAIL = "DATA_FETCH_FAIL";
export const DATA_FETCH_SUCCESS = "DATA_FETCH_SUCCESS";

// product detail page
export const PRODUCT_DETAIL_REQUEST = "PRODUCT_DETAIL_REQUEST";
export const PRODUCT_DETAIL_REQUEST_SUCCESS = "PRODUCT_DETAIL_REQUEST_SUCCESS";
export const PRODUCT_DETAIL_REQUEST_FAIL = "PRODUCT_DETAIL_REQUEST_FAIL";
export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_TO_CART_FAIL = "ADD_TO_CART_FAIL";
export const UPDATE_PURCHASE_QTY = "UPDATE_PURCHASE_QTY";
export const UPDATE_PURCHASE_QTY_FAIL = "UPDATE_PURCHASE_QTY_FAIL";

// shopping cart
export const CARTLIST_ITEM_UPDATE = "CARTLIST_ITEM_UPDATE";
export const CARTLIST_ITEM_UPDATE_FAIL = "CARTLIST_ITEM_UPDATE_FAIL";
export const ITEM_REMOVE = "ITEM_REMOVE";
export const UPDATE_CART_FROM_LOCAL = "UPDATE_CART_FROM_LOCAL";
export const GET_CARTLIST_SUBTOTAL = "GET_CARTLIST_SUBTOTAL";
export const GET_CARTLIST_SUM_PRICE = "GET_CARTLIST_SUM_PRICE";

//filter
export const FILTER_RESET = "FILTER_RESET";
export const SORT_PRICE_ASC = "SORT_PRICE_ASC";
export const SORT_PRICE_DES = "SORT_PRICE_DES";
export const SORT_RATING_ASC = "SORT_RATING_ASC";
export const SORT_RATING_DES = "SORT_RATING_DES";
export const SORT_REVIEW_ASC = "SORT_REVIEW_ASC";
export const SORT_REVIEW_DES = "SORT_REVIEW_DES";
export const MIN_MAX_PRICE = "MIN_MAX_PRICE";
export const SELECT_BY_BRANDS = "SELECT_BY_BRANDS";
export const INTERSECT_FILTER = "INTERSECT_FILTER";
export const SORT_INTERSECT_FILTER = "SORT_INTERSECT_FILTER";
export const MIN_PRICE = "MIN_PRICE";
export const MAX_PRICE = "MAX_PRICE";
export const GET_BRANDS = "GET_BRANDS";
export const BRAND_TOGGLE = "BRAND_TOGGLE";
export const GET_SELECTED_BRANDS = "GET_SELECTED_BRANDS";
export const GET_FILTERED_PRODUCTS = "GET_FILTERED_PRODUCTS";
